language: elixir
elixir: '1.7.4'
otp_release: '21.0'
services:
  - mysql
  - docker

env:
  - MIX_ENV=travis

before_script:
  - mix ecto.create
  - mix ecto.migrate

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master

cache:
  directories:
    - _build
    - deps
