language: elixir
elixir: '1.7.4'
otp_release: '21.0'
services:
  - mysql

env:
  - MIX_ENV=travis

before_script:
  - mix ecto.create
  - mix ecto.migrate

cache:
  directories:
    - _build
    - deps
