apiVersion: v1
kind: Service
metadata:
  name: simplebank-mysql
  labels:
    app: simplebank
spec:
  ports:
    - port: 3306
  selector:
    app: simplebank
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: simplebank-mysql-pv-claim
  labels:
    app: simplebank
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: simplebank-mysql
  labels:
    app: simplebank
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: simplebank
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
          # $ kubectl create secret generic simplebank-mysql-pass --from-file=password.txt
          # make sure password.txt does not have a trailing newline
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: simplebank-mysql-pass
              key: password.txt
        ports:
        - containerPort: 3306
          name: sb-mysql
        volumeMounts:
        - name: simplebank-mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: simplebank-mysql-persistent-storage
        persistentVolumeClaim:
          claimName: simplebank-mysql-pv-claim