apiVersion: v1
kind: Service
metadata:
  name: simplebank-lb
  labels:
    app: simplebank
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: simplebank
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplebank-deployment
  labels:
    app: simplebank
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simplebank
      tier: frontend
  template:
    metadata:
      labels:
        app: simplebank
        tier: frontend
    spec:
      containers:
      - name: simplebank
        image: jonhkr/simplebank:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        volumeMounts:
          - name: config
            mountPath: "/app/config"
            readOnly: true
      volumes:
      - name: config
        secret:
          secretName: simplebank-config